name: cloudphy
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2022.6.15=py38haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ipykernel=6.20.2=pyh025b116_0
  - ipython=8.8.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=5.1.3=py38haa244fe_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1o=h2bbff1b_0
  - packaging=23.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=21.2.2=py38haa95532_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - python=3.8.13=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywin32=227=py38h294d835_1
  - pyzmq=22.3.0=py38hd77b12b_2
  - setuptools=61.2.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.5=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py38h294d835_0
  - traitlets=5.8.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py38haa95532_2
  - pip:
    - aiofiles==22.1.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - altair==4.2.0
    - anyio==3.6.2
    - astor==0.8.1
    - async-timeout==4.0.2
    - attrdict==2.0.1
    - attrs==22.2.0
    - babel==2.11.0
    - bce-python-sdk==0.8.74
    - beautifulsoup4==4.11.1
    - brotli==1.0.9
    - cachetools==5.2.1
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - contourpy==1.0.7
    - cssselect==1.2.0
    - cssutils==2.6.0
    - cycler==0.11.0
    - cython==0.29.33
    - dill==0.3.6
    - et-xmlfile==1.1.0
    - fastapi==0.89.1
    - ffmpy==0.3.0
    - filelock==3.9.0
    - fire==0.5.0
    - flask==2.2.2
    - flask-babel==3.0.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - future==0.18.3
    - gevent==22.10.2
    - geventhttpclient==2.0.8
    - gradio==3.16.2
    - greenlet==2.0.1
    - grpcio==1.41.0
    - h11==0.14.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - huggingface-hub==0.11.1
    - idna==3.4
    - imageio==2.24.0
    - imgaug==0.4.0
    - importlib-metadata==6.0.0
    - importlib-resources==5.10.2
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - linkify-it-py==1.0.3
    - lmdb==1.4.0
    - lxml==4.9.2
    - markdown-it-py==2.1.0
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mpmath==1.2.1
    - multidict==6.0.4
    - multiprocess==0.70.14
    - networkx==3.0
    - numpy==1.23.1
    - onnx==1.13.0
    - opencv-contrib-python==4.7.0.68
    - opencv-python==4.7.0.68
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - orjson==3.8.5
    - paddle-bfloat==0.1.7
    - paddleocr==2.6.1.2
    - paddlepaddle==2.4.1
    - pandas==1.5.3
    - pdf2docx==0.5.6
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - premailer==3.10.0
    - protobuf==3.20.3
    - psutil==5.9.4
    - pyclipper==1.3.0.post4
    - pycparser==2.21
    - pycryptodome==3.16.0
    - pydantic==1.10.4
    - pydub==0.25.1
    - pymupdf==1.20.2
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pytesseract==0.3.10
    - python-docx==0.8.11
    - python-multipart==0.0.5
    - python-rapidjson==1.9
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - rapidfuzz==2.13.7
    - rarfile==4.0
    - regex==2022.10.31
    - requests==2.28.2
    - rfc3986==1.5.0
    - scikit-image==0.19.3
    - scipy==1.10.0
    - shapely==2.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - starlette==0.22.0
    - sympy==1.11.1
    - termcolor==2.2.0
    - tifffile==2022.10.10
    - tokenizers==0.13.2
    - toolz==0.12.0
    - torch==1.13.1
    - tqdm==4.64.1
    - transformers==4.25.1
    - tritonclient==2.22.0
    - uc-micro-py==1.0.1
    - urllib3==1.26.14
    - uvicorn==0.20.0
    - visualdl==2.5.0
    - websockets==10.4
    - werkzeug==2.2.2
    - x2paddle==1.4.0
    - yarl==1.8.2
    - zipp==3.11.0
    - zope-event==4.6
    - zope-interface==5.5.2
prefix: E:\anaconda\envs\paddle_ocr
